apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-dagpeenger-behandling-test
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 2016
  acl:
    - team: teamdagpenger
      application: dp-iverksett
      access: readwrite
    - team: ptsak
      application: pt-sak-dagpenger-dev
      access: read
    - team: ptsak
      application: pt-sak-dagpenger-preprod
      access: read