apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-dagpenger-vedtak-v1
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: -1
  acl:
    - team: teamdagpenger
      application: dp-iverksett
      access: readwrite
    - team: dv-familie
      application: dvh-famef-konsumer
      access: read
    - team: dv-familie
      application: dvh-familie-konsument
      access: read