apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-ef-overgangstonad-v1
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 1440
  acl:
    - team: teamdagpenger
      application: dp-iverksett
      access: read
    - team: teamdagpenger
      application: dp-mottak
      access: read
