apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-dagpenger-iverksatt-vedtak
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  pool: nav-dev
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 720
  acl:
    - team: teamdagpenger
      application: dp-iverksett
      access: readwrite
    - team: teamdagpenger
      application: dp-mottak
      access: read