#######
# Denne er brukt til å gjøre det mulig å bruke tokens lokalt
#
# secret kan hentes fra cluster med "kubectl -n teamdagpenger get secret azuread-dp-iverksett-lokal -o json | jq '.data | map_values(@base64d)'"
#
# Kjøres en gang eller ved endringer med
# kubectl apply -f .deploy/azure-ad-app-lokal.yaml
###
apiVersion: nais.io/v1
kind: AzureAdApplication
metadata:
  name: dp-iverksett-lokal
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  claims:
    groups:
      - id: "928636f4-fd0d-4149-978e-a6fb68bb19de" # 0000-GA-STDAPPS gir tilgang til prosessering
      - id: "97140b9a-07c5-414c-beeb-69824d04c044" # 0000-GA-Dagpenger-Prosessering-Admin gir tilgang til prosessering
      - id: "3e28466f-c53d-46da-8b44-a4abc2ad4593" # 0000-GA-Dagpenger-Saksbehandler
      - id: "11b8475a-fb12-41aa-b1f6-8497c1b5385b" # 0000-GA-Dagpenger-Beslutter
  preAuthorizedApplications:
    - application: dp-iverksett-lokal
      cluster: dev-gcp
      namespace: teamdagpenger
  replyUrls:
    - url: "http://localhost:8000/auth/openid/callback"
  logoutUrl: "http://localhost:8000"
  tenant: trygdeetaten.no
  secretName: azuread-dp-iverksett-lokal