apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: dp-iverksett
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  image: {{ image }}
  ingresses:
    - https://dp-iverksett.intern.dev.nav.no
  liveness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  readiness:
    path: /internal/isAlive
    initialDelay: 30
    failureThreshold: 10
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 1024Mi
      cpu: 1500m
    requests:
      memory: 512Mi
      cpu: 500m
  secureLogs:
    enabled: true
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
    - name: BESLUTTER_ROLLE
      value: "11b8475a-fb12-41aa-b1f6-8497c1b5385b"
  azure:
    application:
      enabled: true
      claims:
        groups:
          - id: "928636f4-fd0d-4149-978e-a6fb68bb19de"  # 0000-GA-STDAPPS gir tilgang til prosessering
  accessPolicy:
    inbound:
      rules:
        - application: dp-iverksett # For testing; kan finne bruken token for app'en til å kalle seg selv
        - application: dp-vedtak
        - application: dp-vedtak-iverksett
        - application: dp-sak-lokal # TODO Navnet på vedtaksløsningen
        - application: dp-prosessering #frontend for task-rammeverket
        - application: dp-ekstern-integrasjon #Tilgang til vedtaksdata via maskinporten
        - application: dp-datadeling
        - application: dp-saksbehandling-frontend
    outbound:
      rules:
        - application: dp-tilbake
        - application: dp-oppdrag
      external:
        - host: dp-oppdrag.dev-gcp-pub.nais.io
        - host: unleash.nais.io
  gcp:
    sqlInstances:
      - type: POSTGRES_14 # IF This is changed, all data will be lost. Read on nais.io how to upgrade
        diskAutoresize: true
        cascadingDelete: true
        pointInTimeRecovery: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: dp-iverksett-2
            envVarPrefix: DB
  kafka:
    pool: nav-dev
