apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  name: aapen-dagpenger-vedtak-arbeidsoppfolging
  namespace: teamdagpenger
  labels:
    team: teamdagpenger
spec:
  pool: nav-prod
  config:
    cleanupPolicy: delete
    minimumInSyncReplicas: 2
    partitions: 1
    replication: 3
    retentionBytes: -1
    retentionHours: 2016
  acl:
    - team: teamdagpenger
      application: dp-iverksett
      access: readwrite
    - team: pto
      application: veilarbportefolje
      access: read